package clientInt.WordyModule;


/**
* clientInt/WordyModule/NotEnoughPlayers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class NotEnoughPlayers extends org.omg.CORBA.UserException
{

  //Not enough players to start the game
  public String reason = null;

  public NotEnoughPlayers ()
  {
    super(NotEnoughPlayersHelper.id());
  } // ctor

  public NotEnoughPlayers (String _reason)
  {
    super(NotEnoughPlayersHelper.id());
    reason = _reason;
  } // ctor


  public NotEnoughPlayers (String $reason, String _reason)
  {
    super(NotEnoughPlayersHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NotEnoughPlayers
