package clientInt.WordyModule;


/**
* clientInt/WordyModule/TopLongestWord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class TopLongestWord implements org.omg.CORBA.portable.IDLEntity
{

  //Longest words leaderboard entry
  public String username = null;
  public String word = null;
  public int letterCount = (int)0;

  public TopLongestWord ()
  {
  } // ctor

  public TopLongestWord (String _username, String _word, int _letterCount)
  {
    username = _username;
    word = _word;
    letterCount = _letterCount;
  } // ctor

} // class TopLongestWord
