package clientInt.WordyModule;


/**
* clientInt/WordyModule/TopPlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class TopPlayer implements org.omg.CORBA.portable.IDLEntity
{

  //Most wins leaderboard entry
  public String username = null;
  public int roundWins = (int)0;
  public int gameWins = (int)0;

  public TopPlayer ()
  {
  } // ctor

  public TopPlayer (String _username, int _roundWins, int _gameWins)
  {
    username = _username;
    roundWins = _roundWins;
    gameWins = _gameWins;
  } // ctor

} // class TopPlayer
