# DO NOT EDIT THIS FILE!
#
# Python module WordyModule__POA generated by omniidl

import omniORB
omniORB.updateModule("WordyModule__POA")

# ** 1. Stub files contributing to this module
import wordy_idl

# ** 2. Sub-modules

# ** 3. End
