package serverInt.WordyModule;


/**
* serverInt/WordyModule/InvalidLoginException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class InvalidLoginException extends org.omg.CORBA.UserException
{

  //Wrong username/password or username does not exist in the database
  public String reason = null;

  public InvalidLoginException ()
  {
    super(InvalidLoginExceptionHelper.id());
  } // ctor

  public InvalidLoginException (String _reason)
  {
    super(InvalidLoginExceptionHelper.id());
    reason = _reason;
  } // ctor


  public InvalidLoginException (String $reason, String _reason)
  {
    super(InvalidLoginExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidLoginException
