package serverInt.WordyModule;

/**
* serverInt/WordyModule/NotEnoughPlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class NotEnoughPlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public serverInt.WordyModule.NotEnoughPlayers value = null;

  public NotEnoughPlayersHolder ()
  {
  }

  public NotEnoughPlayersHolder (serverInt.WordyModule.NotEnoughPlayers initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverInt.WordyModule.NotEnoughPlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverInt.WordyModule.NotEnoughPlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverInt.WordyModule.NotEnoughPlayersHelper.type ();
  }

}
