package serverInt.WordyModule;


/**
* serverInt/WordyModule/NoWinnerException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class NoWinnerException extends org.omg.CORBA.UserException
{

  //2) Tie between players
  public String reason = null;

  public NoWinnerException ()
  {
    super(NoWinnerExceptionHelper.id());
  } // ctor

  public NoWinnerException (String _reason)
  {
    super(NoWinnerExceptionHelper.id());
    reason = _reason;
  } // ctor


  public NoWinnerException (String $reason, String _reason)
  {
    super(NoWinnerExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NoWinnerException
