package serverInt.WordyModule;


/**
* serverInt/WordyModule/PlayerListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class PlayerListHolder implements org.omg.CORBA.portable.Streamable
{
  public serverInt.WordyModule.Player_ value[] = null;

  public PlayerListHolder ()
  {
  }

  public PlayerListHolder (serverInt.WordyModule.Player_[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverInt.WordyModule.PlayerListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverInt.WordyModule.PlayerListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverInt.WordyModule.PlayerListHelper.type ();
  }

}
