package serverInt.WordyModule;

/**
* serverInt/WordyModule/RoundWinner_Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class RoundWinner_Holder implements org.omg.CORBA.portable.Streamable
{
  public serverInt.WordyModule.RoundWinner_ value = null;

  public RoundWinner_Holder ()
  {
  }

  public RoundWinner_Holder (serverInt.WordyModule.RoundWinner_ initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverInt.WordyModule.RoundWinner_Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverInt.WordyModule.RoundWinner_Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverInt.WordyModule.RoundWinner_Helper.type ();
  }

}
