package serverInt.WordyModule;


/**
* serverInt/WordyModule/RoundWinner_Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

abstract public class RoundWinner_Helper
{
  private static String  _id = "IDL:WordyModule/RoundWinner_:1.0";

  public static void insert (org.omg.CORBA.Any a, serverInt.WordyModule.RoundWinner_ that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static serverInt.WordyModule.RoundWinner_ extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "winningWord",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "roundWins",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (serverInt.WordyModule.RoundWinner_Helper.id (), "RoundWinner_", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static serverInt.WordyModule.RoundWinner_ read (org.omg.CORBA.portable.InputStream istream)
  {
    serverInt.WordyModule.RoundWinner_ value = new serverInt.WordyModule.RoundWinner_ ();
    value.name = istream.read_string ();
    value.winningWord = istream.read_string ();
    value.roundWins = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, serverInt.WordyModule.RoundWinner_ value)
  {
    ostream.write_string (value.name);
    ostream.write_string (value.winningWord);
    ostream.write_long (value.roundWins);
  }

}
