package serverInt.WordyModule;

/**
* serverInt/WordyModule/TopPlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class TopPlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public serverInt.WordyModule.TopPlayer value = null;

  public TopPlayerHolder ()
  {
  }

  public TopPlayerHolder (serverInt.WordyModule.TopPlayer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverInt.WordyModule.TopPlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverInt.WordyModule.TopPlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverInt.WordyModule.TopPlayerHelper.type ();
  }

}
