package serverInt.WordyModule;


/**
* serverInt/WordyModule/WordyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public abstract class WordyPOA extends org.omg.PortableServer.Servant
 implements serverInt.WordyModule.WordyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("logout", new java.lang.Integer (1));
    _methods.put ("initiateGame", new java.lang.Integer (2));
    _methods.put ("submitWord", new java.lang.Integer (3));
    _methods.put ("getGameWinner", new java.lang.Integer (4));
    _methods.put ("getAllPlayers", new java.lang.Integer (5));
    _methods.put ("getRoundWinner", new java.lang.Integer (6));
    _methods.put ("getLetters", new java.lang.Integer (7));
    _methods.put ("getTime", new java.lang.Integer (8));
    _methods.put ("getLongestWord", new java.lang.Integer (9));
    _methods.put ("getLongestWordsSize", new java.lang.Integer (10));
    _methods.put ("getTopPlayers", new java.lang.Integer (11));
    _methods.put ("getTopPlayersSize", new java.lang.Integer (12));
    _methods.put ("disposeGame", new java.lang.Integer (13));
    _methods.put ("gameStartFlag", new java.lang.Integer (14));
    _methods.put ("gameEndFlag", new java.lang.Integer (15));
    _methods.put ("roundEndFlag", new java.lang.Integer (16));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WordyModule/Wordy/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           this.login (username, password);
           out = $rh.createReply();
         } catch (serverInt.WordyModule.InvalidLoginException $ex) {
           out = $rh.createExceptionReply ();
           serverInt.WordyModule.InvalidLoginExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // WordyModule/Wordy/logout
       {
         String username = in.read_string ();
         this.logout (username);
         out = $rh.createReply();
         break;
       }

       case 2:  // WordyModule/Wordy/initiateGame
       {
         try {
           String username = in.read_string ();
           this.initiateGame (username);
           out = $rh.createReply();
         } catch (serverInt.WordyModule.NotEnoughPlayers $ex) {
           out = $rh.createExceptionReply ();
           serverInt.WordyModule.NotEnoughPlayersHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // WordyModule/Wordy/submitWord
       {
         try {
           String username = in.read_string ();
           String word = in.read_string ();
           this.submitWord (username, word);
           out = $rh.createReply();
         } catch (serverInt.WordyModule.InvalidWordException $ex) {
           out = $rh.createExceptionReply ();
           serverInt.WordyModule.InvalidWordExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // WordyModule/Wordy/getGameWinner
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getGameWinner (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // WordyModule/Wordy/getAllPlayers
       {
         String username = in.read_string ();
         serverInt.WordyModule.Player_ $result[] = null;
         $result = this.getAllPlayers (username);
         out = $rh.createReply();
         serverInt.WordyModule.PlayerListHelper.write (out, $result);
         break;
       }

       case 6:  // WordyModule/Wordy/getRoundWinner
       {
         try {
           String username = in.read_string ();
           serverInt.WordyModule.RoundWinner_ $result = null;
           $result = this.getRoundWinner (username);
           out = $rh.createReply();
           serverInt.WordyModule.RoundWinner_Helper.write (out, $result);
         } catch (serverInt.WordyModule.NoWinnerException $ex) {
           out = $rh.createExceptionReply ();
           serverInt.WordyModule.NoWinnerExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // WordyModule/Wordy/getLetters
       {
         String username = in.read_string ();
         char $result[] = null;
         $result = this.getLetters (username);
         out = $rh.createReply();
         serverInt.WordyModule.LettersHelper.write (out, $result);
         break;
       }

       case 8:  // WordyModule/Wordy/getTime
       {
         String username = in.read_string ();
         int $result = (int)0;
         $result = this.getTime (username);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 9:  // WordyModule/Wordy/getLongestWord
       {
         int index = in.read_long ();
         serverInt.WordyModule.TopLongestWord $result = null;
         $result = this.getLongestWord (index);
         out = $rh.createReply();
         serverInt.WordyModule.TopLongestWordHelper.write (out, $result);
         break;
       }

       case 10:  // WordyModule/Wordy/getLongestWordsSize
       {
         int $result = (int)0;
         $result = this.getLongestWordsSize ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 11:  // WordyModule/Wordy/getTopPlayers
       {
         int index = in.read_long ();
         serverInt.WordyModule.TopPlayer $result = null;
         $result = this.getTopPlayers (index);
         out = $rh.createReply();
         serverInt.WordyModule.TopPlayerHelper.write (out, $result);
         break;
       }

       case 12:  // WordyModule/Wordy/getTopPlayersSize
       {
         int $result = (int)0;
         $result = this.getTopPlayersSize ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 13:  // WordyModule/Wordy/disposeGame
       {
         String username = in.read_string ();
         this.disposeGame (username);
         out = $rh.createReply();
         break;
       }

       case 14:  // WordyModule/Wordy/gameStartFlag
       {
         String username = in.read_string ();
         boolean $result = false;
         $result = this.gameStartFlag (username);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 15:  // WordyModule/Wordy/gameEndFlag
       {
         String username = in.read_string ();
         boolean $result = false;
         $result = this.gameEndFlag (username);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 16:  // WordyModule/Wordy/roundEndFlag
       {
         String username = in.read_string ();
         boolean $result = false;
         $result = this.roundEndFlag (username);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordyModule/Wordy:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Wordy _this() 
  {
    return WordyHelper.narrow(
    super._this_object());
  }

  public Wordy _this(org.omg.CORBA.ORB orb) 
  {
    return WordyHelper.narrow(
    super._this_object(orb));
  }


} // class WordyPOA
