package serverInt.WordyModule;

/**
* serverInt/WordyModule/WordyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Sunday, July 2, 2023 2:41:05 PM CST
*/

public final class WordyHolder implements org.omg.CORBA.portable.Streamable
{
  public serverInt.WordyModule.Wordy value = null;

  public WordyHolder ()
  {
  }

  public WordyHolder (serverInt.WordyModule.Wordy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverInt.WordyModule.WordyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverInt.WordyModule.WordyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverInt.WordyModule.WordyHelper.type ();
  }

}
